openapi: 3.0.1
info:
  title: PDND_Curit_Erogazione
  description: CURIT - Catasto Unico Regionale Impianti Termici – Impianti Targati
  version: v1.0.0
servers:
- url: /
paths:
  /about_data:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components: {}
x-original-swagger-version: "2.0"
