openapi: 3.0.1
info:
  title: Consultazione dei dati della programmazione dell'offerta abitativa pubblica e sociale lombarda
  description: Tale servizio potenzia la raccolta e la trasmissione dei dati provenienti dai Pronto Soccorso presenti nel territorio lombardo, mettendo a disposizione informazioni dettagliate relative all'afflusso dei pazienti in PS, ai tempi di attesa medi, alle patologie e alle specialità.
  version: v1.0
  contact:
    # Contatti API Provider 
    name: Assistenza API
    email: assistenza_api@regione.lombardia.it

servers:
    - url: https://api.integrazione.lispa.it/c/pdndbasic/erogazione/serviziabitativi
      description: Url in ambiente di Collaudo PDND
    - url: https://api.servizirl.it/c/pdndbasic/erogazione/serviziabitativi
      description: Url in ambiente di Produzione PDND

paths:
  # Ulteriori dettagli relativi alla costruzione delle chiamate sono riportati nella documentazione tecnica
    #parameters:
       # $ref: '#/externalDocs'

  /context/rest/get/elencoComposizionePianiZona:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


  /context/rest/get/recuperoCategoria:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /context/rest/get/recuperoAlloggiPiano:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /context/rest/get/offertaTriennale:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


  /context/rest/get/offertaAnnuale:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

components: {}
externalDocs: 
  description: Documento di Specifiche Tecniche per Consultazione dei dati della programmazione dell'offerta abitativa pubblica e sociale lombarda
  url: https://github.com/RegioneLombardia/PDND/blob/main/e-services/ConsultazioneProgrammazioneOffertaAbitativa/ConsultazioneProgrammazioneOffertaAbitativa_ManualeUtente.pdf