<?xml version='1.0' encoding='UTF-8'?><definitions xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://interop.servizirl.it/schema/ws/richiestapratica/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:richiestapratica="http://interop.servizirl.it/schema/richiestapratica/1.0" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://interop.servizirl.it/schema/ws/richiestapratica/1.0">
<documentation>
      Versione 1.0
  </documentation>
  <types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://interop.servizirl.it/schema/ws/richiestapratica/1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:richiestapratica="http://interop.servizirl.it/schema/richiestapratica/1.0" xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
			
  <xs:import namespace="http://interop.servizirl.it/schema/richiestapratica/1.0" schemaLocation="https://api.servizirl.it/c/pdndbasic/erogazione/mutahub/services/ws/RichiestaPraticaWSServiceSAUAR?xsd=schema-richiestapratica-types.xsd"/>
		
</xs:schema>
  </types>
  <message name="richiesta_RichiestaRispostaSincrona_RichiestaPratica_Msg">
    <part element="richiestapratica:RichiestaPratica" name="parameter">
    </part>
  </message>
  <message name="risposta_RichiestaRispostaSincrona_RichiestaPratica_Msg">
    <part element="richiestapratica:RispostaRichiestaPratica" name="return">
    </part>
  </message>
  <portType name="RichiestaPraticaWSPortType">
    <operation name="RichiestaRispostaSincrona_RichiestaPratica">
      <input message="tns:richiesta_RichiestaRispostaSincrona_RichiestaPratica_Msg">
    </input>
      <output message="tns:risposta_RichiestaRispostaSincrona_RichiestaPratica_Msg">
    </output>
    </operation>
  </portType>
  <binding name="RichiestaPraticaWSPortBinding" type="tns:RichiestaPraticaWSPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="RichiestaRispostaSincrona_RichiestaPratica">
      <soap:operation soapAction="RichiestaRispostaSincrona_RichiestaPratica"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="RichiestaPraticaWSService">
    <port binding="tns:RichiestaPraticaWSPortBinding" name="RichiestaPraticaWSPort">
      <soap:address location="https://api.servizirl.it/c/pdndbasic/erogazione/mutahub/services/ws/RichiestaPraticaWSServiceSAUAR"/>
    </port>
  </service>
</definitions>