openapi: 3.0.1
info:
  title: Agriturismi in Lombardia
  description: Il servizio permette di svolgere la ricerca di dati specifici afferenti gli agriturismi presenti nel territorio lombardo. La banca dati è alimentata dall'applicazione gestionale Osservatorio Agriturismi di Regione Lombardia.
  version: v1.0
  contact:
    # Contatti API Provider 
    name: Assistenza API
    email: assistenza_api@regione.lombardia.it

servers:
    - url: https://api.integrazione.lispa.it/c/pdndbasic/erogazione/webagri-api
      description: Url in ambiente di Collaudo PDND
    - url: https://api.servizirl.it/c/pdndbasic/erogazione/webagri-api
      description: Url in ambiente di Produzione PDND

paths:
  # Ulteriori dettagli relativi alla costruzione delle chiamate sono riportati nella documentazione tecnica
    #parameters:
       # $ref: '#/externalDocs'

  /rest/categServWeb/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/categorieProd/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/categInfoTurist/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

 
  /rest/servizi/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/prodotti/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/province/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/comuni/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/territori/getAll:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/ricercaLibera:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/ricercaAgriServizi:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/ricercaAgriTerritori:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/getApertureAgriturismo:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/getInfoTuristAgriturismo:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /rest/foto/getAllByIdAzienda:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


components: {}
externalDocs: 
  description: Documento di Specifiche Tecniche per l'API Agriturismi in Lombardia
  url: https://github.com/RegioneLombardia/PDND/blob/main/e-services/AgriturismiInLombardia/AgriturismiInLombardia_ManualeUtente.pdf
