openapi: 3.0.1
info:
  title: Accessibilita Delle Strutture In Lombardia
  description: Il servizio permette di ottenere la lista di strutture accessibili (es. musei, monumenti) di interesse turistico-culturale del territorio lombardo. I criteri di ricerca possono essere di tipo geografico, oppure riguardare la tipologia della struttura o i servizi di accessibilità richiesti.
  version: v1.0
  contact:
    # Contatti API Provider 
    name: Assistenza API
    email: assistenza_api@regione.lombardia.it

servers:
    - url: https://api.integrazione.lispa.it/c/pdndbasic/erogazione/accessibilitaStrutture
      description: Url in ambiente di Collaudo PDND
    - url: https://api.servizirl.it/c/pdndbasic/erogazione/accessibilitaStrutture
      description: Url in ambiente di Produzione PDND

paths:
  # Ulteriori dettagli relativi alla costruzione delle chiamate sono riportati nella documentazione tecnica
    #parameters:
       # $ref: '#/externalDocs'

  /venue-list:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /get-venue:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


  /venue-list-by-id:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


components: {}
externalDocs: 
  description: Documento di Specifiche Tecniche per L'API Accessibilita Delle Strutture In Lombardia
  url: https://github.com/RegioneLombardia/PDND/blob/main/e-services/AccessibilitaDelleStruttureInLombardia/AccessibilitaDelleStruttureInLombardia_ManualeUtente.pdf
