openapi: 3.0.1
info:
  title: Accessibilita Delle Strutture In Lombardia
  description: ll servizio consente di ottenere la lista delle strutture accessibili nella Regione Lombardia. Ogni elemento censito all’interno del portale Lombardia Facile contiene informazioni che definiscono categoria di appartenenza, descrizione, indirizzo, coordinate geografiche e tutto quanto sia rilevante per individui affetti da disabilità.
  version: v1.0
  contact:
    # Contatti API Provider 
    name: Assistenza API
    email: assistenza_api@regione.lombardia.it

servers:
    - url: https://api.integrazione.lispa.it/c/pdndbasic/erogazione/accessibilitaStrutture
      description: Url in ambiente di Collaudo PDND
    - url: https://api.servizirl.it/c/pdndbasic/erogazione/accessibilitaStrutture
      description: Url in ambiente di Produzione PDND

paths:
  # Ulteriori dettagli relativi alla costruzione delle chiamate sono riportati nella documentazione tecnica
    #parameters:
       # $ref: '#/externalDocs'

  /venue-list:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

  /get-venue:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


  /venue-list-by-id:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


components: {}
externalDocs: 
  description: Documento di Specifiche Tecniche per Strutture Accessibili in Lombardia
  url: https://github.com/RegioneLombardia/PDND/blob/main/e-services/StruttureAccessibiliInLombardia/StruttureAccessibiliInLombardia_ManualeUtente.pdf