openapi: 3.0.1
info:
  title: Punti vendita per Celiaci 
  description: Il SEB CELI-API mette a disposizione i servizi inerenti le funzionalità di consultazione dei punti erogazione aderenti al progetto regionale Celiachia per la distribuzione di alimenti senza glutine e i servizi di ricerca per prossimità.
  version: v1.0
  contact:
    # Contatti API Provider 
    name: Assistenza API
    email: assistenza_api@regione.lombardia.it

servers:
    - url: https://api.integrazione.lispa.it/c/pdndbasic/erogazione/siss/celiachia_forn
      description: Url in ambiente di Collaudo PDND
    - url: https://api.servizirl.it/c/pdndbasic/erogazione/siss/celiachia_forn
      description: Url in ambiente di Produzione PDND

paths:
  # Ulteriori dettagli relativi alla costruzione delle chiamate sono riportati nella documentazione tecnica
    #parameters:
       # $ref: '#/externalDocs'

  /getPuntiErogazione:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload




  /getProximityByCircle:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload


  /getIncrementalProximityByCircle:
    get:
      responses:
        "200":
          description: ""
          content: {}
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-codegen-request-body-name: Payload

components: {}
externalDocs: 
  description: Documento di Specifiche Tecniche per API SEB CELI-API
  url: https://github.com/RegioneLombardia/PDND/blob/main/e-services/PuntiVenditaPerCeliaci/PuntiVenditaPerCeliaci_ManualeUtente.pdf
